CREATE TABLE "user_role" (
    "USER_ID" UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    "description" VARCHAR(60) NOT NULL,
    CONSTRAINT fk_user_id FOREIGN KEY (USER_ID) REFERENCES "user"("id") ON DELETE CASCADE
);